<?php

namespace App\Http\Livewire\Forms;

use App\API\npi\Client;
use GuzzleHttp\Exception\GuzzleException;
use Livewire\Component;

class NpiSearch extends Component
{
    public array $states = [
        ['state_abbreviation' => 'AL', 'state_name' => 'Alabama'],
        ['state_abbreviation' => 'AK', 'state_name' => 'Alaska'],
        ['state_abbreviation' => 'AS', 'state_name' => 'American Samoa'],
        ['state_abbreviation' => 'AZ', 'state_name' => 'Arizona'],
        ['state_abbreviation' => 'AR', 'state_name' => 'Arkansas'],
        ['state_abbreviation' => 'AA', 'state_name' => 'Armed Forces America'],
        ['state_abbreviation' => 'AE', 'state_name' => 'Armed Forces Europe /Canada / Middle East / Africa'],
        ['state_abbreviation' => 'AP', 'state_name' => 'Armed Forces Pacific'],
        ['state_abbreviation' => 'CA', 'state_name' => 'California'],
        ['state_abbreviation' => 'CO', 'state_name' => 'Colorado'],
        ['state_abbreviation' => 'CT', 'state_name' => 'Connecticut'],
        ['state_abbreviation' => 'DE', 'state_name' => 'Delaware'],
        ['state_abbreviation' => 'DC', 'state_name' => 'District of Columbia'],
        ['state_abbreviation' => 'FM', 'state_name' => 'Federated States of Micronesia'],
        ['state_abbreviation' => 'FL', 'state_name' => 'Florida'],
        ['state_abbreviation' => 'GA', 'state_name' => 'Georgia'],
        ['state_abbreviation' => 'GU', 'state_name' => 'Guam'],
        ['state_abbreviation' => 'HI', 'state_name' => 'Hawaii'],
        ['state_abbreviation' => 'ID', 'state_name' => 'Idaho'],
        ['state_abbreviation' => 'IL', 'state_name' => 'Illinois'],
        ['state_abbreviation' => 'IN', 'state_name' => 'Indiana'],
        ['state_abbreviation' => 'IA', 'state_name' => 'Iowa'],
        ['state_abbreviation' => 'KS', 'state_name' => 'Kansas'],
        ['state_abbreviation' => 'KY', 'state_name' => 'Kentucky'],
        ['state_abbreviation' => 'LA', 'state_name' => 'Louisiana'],
        ['state_abbreviation' => 'ME', 'state_name' => 'Maine'],
        ['state_abbreviation' => 'MP', 'state_name' => 'Mariana Islands, Northern'],
        ['state_abbreviation' => 'MH', 'state_name' => 'Marshall Islands'],
        ['state_abbreviation' => 'MD', 'state_name' => 'Maryland'],
        ['state_abbreviation' => 'MA', 'state_name' => 'Massachusetts'],
        ['state_abbreviation' => 'MI', 'state_name' => 'Michigan'],
        ['state_abbreviation' => 'MN', 'state_name' => 'Minnesota'],
        ['state_abbreviation' => 'MS', 'state_name' => 'Mississippi'],
        ['state_abbreviation' => 'MO', 'state_name' => 'Missouri'],
        ['state_abbreviation' => 'MT', 'state_name' => 'Montana'],
        ['state_abbreviation' => 'NE', 'state_name' => 'Nebraska'],
        ['state_abbreviation' => 'NV', 'state_name' => 'Nevada'],
        ['state_abbreviation' => 'NH', 'state_name' => 'New Hampshire'],
        ['state_abbreviation' => 'NJ', 'state_name' => 'New Jersey'],
        ['state_abbreviation' => 'NM', 'state_name' => 'New Mexico'],
        ['state_abbreviation' => 'NY', 'state_name' => 'New York'],
        ['state_abbreviation' => 'NC', 'state_name' => 'North Carolina'],
        ['state_abbreviation' => 'ND', 'state_name' => 'North Dakota'],
        ['state_abbreviation' => 'OH', 'state_name' => 'Ohio'],
        ['state_abbreviation' => 'OK', 'state_name' => 'Oklahoma'],
        ['state_abbreviation' => 'OR', 'state_name' => 'Oregon'],
        ['state_abbreviation' => 'PA', 'state_name' => 'Pennsylvania'],
        ['state_abbreviation' => 'PR', 'state_name' => 'Puerto Rico'],
        ['state_abbreviation' => 'RI', 'state_name' => 'Rhode Island'],
        ['state_abbreviation' => 'SC', 'state_name' => 'South Carolina'],
        ['state_abbreviation' => 'SD', 'state_name' => 'South Dakota'],
        ['state_abbreviation' => 'TN', 'state_name' => 'Tennessee'],
        ['state_abbreviation' => 'TX', 'state_name' => 'Texas'],
        ['state_abbreviation' => 'UT', 'state_name' => 'Utah'],
        ['state_abbreviation' => 'VT', 'state_name' => 'Vermont'],
        ['state_abbreviation' => 'VI', 'state_name' => 'Virgin Islands'],
        ['state_abbreviation' => 'VA', 'state_name' => 'Virginia'],
        ['state_abbreviation' => 'WA', 'state_name' => 'Washington'],
        ['state_abbreviation' => 'WV', 'state_name' => 'West Virginia'],
        ['state_abbreviation' => 'WI', 'state_name' => 'Wisconsin'],
        ['state_abbreviation' => 'WY', 'state_name' => 'Wyoming'],
    ];
    public array $countries = [
        ['country_abbreviation' => 'AX', 'country_name' => 'Aland Islands'],
        ['country_abbreviation' => 'AL', 'country_name' => 'Albania'],
        ['country_abbreviation' => 'DZ', 'country_name' => 'Algeria'],
        ['country_abbreviation' => 'AD', 'country_name' => 'Andorra'],
        ['country_abbreviation' => 'AO', 'country_name' => 'Angola'],
        ['country_abbreviation' => 'AI', 'country_name' => 'Anguilla'],
        ['country_abbreviation' => 'AQ', 'country_name' => 'Antarctica'],
        ['country_abbreviation' => 'AG', 'country_name' => 'Antigua and Barbuda'],
        ['country_abbreviation' => 'AR', 'country_name' => 'Argentina'],
        ['country_abbreviation' => 'AM', 'country_name' => 'Armenia'],
        ['country_abbreviation' => 'AW', 'country_name' => 'Aruba'],
        ['country_abbreviation' => 'AU', 'country_name' => 'Australia'],
        ['country_abbreviation' => 'AT', 'country_name' => 'Austria'],
        ['country_abbreviation' => 'AZ', 'country_name' => 'Azerbaijan'],
        ['country_abbreviation' => 'BS', 'country_name' => 'Bahamas'],
        ['country_abbreviation' => 'BH', 'country_name' => 'Bahrain'],
        ['country_abbreviation' => 'BD', 'country_name' => 'Bangladesh'],
        ['country_abbreviation' => 'BB', 'country_name' => 'Barbados'],
        ['country_abbreviation' => 'BY', 'country_name' => 'Belarus'],
        ['country_abbreviation' => 'BE', 'country_name' => 'Belgium'],
        ['country_abbreviation' => 'BZ', 'country_name' => 'Belize'],
        ['country_abbreviation' => 'BJ', 'country_name' => 'Benin'],
        ['country_abbreviation' => 'BM', 'country_name' => 'Bermuda'],
        ['country_abbreviation' => 'BT', 'country_name' => 'Bhutan'],
        ['country_abbreviation' => 'BO', 'country_name' => 'Bolivia'],
        ['country_abbreviation' => 'BA', 'country_name' => 'Bosnia and Herzegovina'],
        ['country_abbreviation' => 'BW', 'country_name' => 'Botswana'],
        ['country_abbreviation' => 'BV', 'country_name' => 'Bouvet Island'],
        ['country_abbreviation' => 'BR', 'country_name' => 'Brazil'],
        ['country_abbreviation' => 'IO', 'country_name' => 'British Indian Ocean Territory'],
        ['country_abbreviation' => 'BN', 'country_name' => 'Brunei Darussalam'],
        ['country_abbreviation' => 'BG', 'country_name' => 'Bulgaria'],
        ['country_abbreviation' => 'BF', 'country_name' => 'Burkina Faso'],
        ['country_abbreviation' => 'BI', 'country_name' => 'Burundi'],
        ['country_abbreviation' => 'KH', 'country_name' => 'Cambodia'],
        ['country_abbreviation' => 'CM', 'country_name' => 'Cameroon'],
        ['country_abbreviation' => 'CA', 'country_name' => 'Canada'],
        ['country_abbreviation' => 'CV', 'country_name' => 'Cape Verde'],
        ['country_abbreviation' => 'KY', 'country_name' => 'Cayman Islands'],
        ['country_abbreviation' => 'CF', 'country_name' => 'Central African Republic'],
        ['country_abbreviation' => 'TD', 'country_name' => 'Chad'],
        ['country_abbreviation' => 'CL', 'country_name' => 'Chile'],
        ['country_abbreviation' => 'CN', 'country_name' => 'China'],
        ['country_abbreviation' => 'CX', 'country_name' => 'Christmas Island'],
        ['country_abbreviation' => 'CC', 'country_name' => 'Cocos (Keeling) Islands'],
        ['country_abbreviation' => 'CO', 'country_name' => 'Colombia'],
        ['country_abbreviation' => 'KM', 'country_name' => 'Comoros'],
        ['country_abbreviation' => 'CG', 'country_name' => 'Congo'],
        ['country_abbreviation' => 'CD', 'country_name' => 'Congo, The Democratic Republic of the'],
        ['country_abbreviation' => 'CK', 'country_name' => 'Cook Islands'],
        ['country_abbreviation' => 'CR', 'country_name' => 'Costa Rica'],
        ['country_abbreviation' => 'HR', 'country_name' => 'Croatia'],
        ['country_abbreviation' => 'CU', 'country_name' => 'Cuba'],
        ['country_abbreviation' => 'CY', 'country_name' => 'Cyprus'],
        ['country_abbreviation' => 'CZ', 'country_name' => 'Czech Republic'],
        ['country_abbreviation' => 'DK', 'country_name' => 'Denmark'],
        ['country_abbreviation' => 'DJ', 'country_name' => 'Djibouti'],
        ['country_abbreviation' => 'DM', 'country_name' => 'Dominica'],
        ['country_abbreviation' => 'DO', 'country_name' => 'Dominican Republic'],
        ['country_abbreviation' => 'EC', 'country_name' => 'Ecuador'],
        ['country_abbreviation' => 'EG', 'country_name' => 'Egypt'],
        ['country_abbreviation' => 'SV', 'country_name' => 'El Salvador'],
        ['country_abbreviation' => 'GQ', 'country_name' => 'Equatorial Guinea'],
        ['country_abbreviation' => 'ER', 'country_name' => 'Eritrea'],
        ['country_abbreviation' => 'EE', 'country_name' => 'Estonia'],
        ['country_abbreviation' => 'ET', 'country_name' => 'Ethiopia'],
        ['country_abbreviation' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)'],
        ['country_abbreviation' => 'FO', 'country_name' => 'Faroe Islands'],
        ['country_abbreviation' => 'FJ', 'country_name' => 'Fiji'],
        ['country_abbreviation' => 'FI', 'country_name' => 'Finland'],
        ['country_abbreviation' => 'FR', 'country_name' => 'France'],
        ['country_abbreviation' => 'GF', 'country_name' => 'French Guiana'],
        ['country_abbreviation' => 'PF', 'country_name' => 'French Polynesia'],
        ['country_abbreviation' => 'TF', 'country_name' => 'French Southern Territories'],
        ['country_abbreviation' => 'GA', 'country_name' => 'Gabon'],
        ['country_abbreviation' => 'GM', 'country_name' => 'Gambia'],
        ['country_abbreviation' => 'GE', 'country_name' => 'Georgia'],
        ['country_abbreviation' => 'DE', 'country_name' => 'Germany'],
        ['country_abbreviation' => 'GH', 'country_name' => 'Ghana'],
        ['country_abbreviation' => 'GI', 'country_name' => 'Gibraltar'],
        ['country_abbreviation' => 'GB', 'country_name' => 'Great Britain'],
        ['country_abbreviation' => 'GR', 'country_name' => 'Greece'],
        ['country_abbreviation' => 'GL', 'country_name' => 'Greenland'],
        ['country_abbreviation' => 'GD', 'country_name' => 'Grenada'],
        ['country_abbreviation' => 'GP', 'country_name' => 'Guadeloupe'],
        ['country_abbreviation' => 'GT', 'country_name' => 'Guatemala'],
        ['country_abbreviation' => 'GG', 'country_name' => 'Guernsey'],
        ['country_abbreviation' => 'GN', 'country_name' => 'Guinea'],
        ['country_abbreviation' => 'GW', 'country_name' => 'Guinea-Bissau'],
        ['country_abbreviation' => 'GY', 'country_name' => 'Guyana'],
        ['country_abbreviation' => 'HT', 'country_name' => 'Haiti'],
        ['country_abbreviation' => 'HM', 'country_name' => 'Heard Island and McDonald Islands'],
        ['country_abbreviation' => 'VA', 'country_name' => 'Holy See (Vatican City State)'],
        ['country_abbreviation' => 'HN', 'country_name' => 'Honduras'],
        ['country_abbreviation' => 'HK', 'country_name' => 'Hong Kong'],
        ['country_abbreviation' => 'HU', 'country_name' => 'Hungary'],
        ['country_abbreviation' => 'IS', 'country_name' => 'Iceland'],
        ['country_abbreviation' => 'IN', 'country_name' => 'India'],
        ['country_abbreviation' => 'ID', 'country_name' => 'Indonesia'],
        ['country_abbreviation' => 'IR', 'country_name' => 'Iran, Islamic Republic of'],
        ['country_abbreviation' => 'IQ', 'country_name' => 'Iraq'],
        ['country_abbreviation' => 'IE', 'country_name' => 'Ireland'],
        ['country_abbreviation' => 'IM', 'country_name' => 'Isle Of Man'],
        ['country_abbreviation' => 'IL', 'country_name' => 'Israel'],
        ['country_abbreviation' => 'IT', 'country_name' => 'Italy'],
        ['country_abbreviation' => 'CI', 'country_name' => 'Ivory Coast'],
        ['country_abbreviation' => 'JM', 'country_name' => 'Jamaica'],
        ['country_abbreviation' => 'JP', 'country_name' => 'Japan'],
        ['country_abbreviation' => 'JE', 'country_name' => 'Jersey'],
        ['country_abbreviation' => 'JO', 'country_name' => 'Jordan'],
        ['country_abbreviation' => 'KZ', 'country_name' => 'Kazakhstan'],
        ['country_abbreviation' => 'KE', 'country_name' => 'Kenya'],
        ['country_abbreviation' => 'KI', 'country_name' => 'Kiribati'],
        ['country_abbreviation' => 'KP', 'country_name' => 'Korea, Democratic People\'s Republic of'],
        ['country_abbreviation' => 'KR', 'country_name' => 'Korea, Republic of'],
        ['country_abbreviation' => 'XK', 'country_name' => 'Kosovo'],
        ['country_abbreviation' => 'KW', 'country_name' => 'Kuwait'],
        ['country_abbreviation' => 'KG', 'country_name' => 'Kyrgyzstan'],
        ['country_abbreviation' => 'LA', 'country_name' => 'Lao People\'s Democratic Republic'],
        ['country_abbreviation' => 'LV', 'country_name' => 'Latvia'],
        ['country_abbreviation' => 'LB', 'country_name' => 'Lebanon'],
        ['country_abbreviation' => 'LS', 'country_name' => 'Lesotho'],
        ['country_abbreviation' => 'LR', 'country_name' => 'Liberia'],
        ['country_abbreviation' => 'LY', 'country_name' => 'Libyan Arab Jamahiriya'],
        ['country_abbreviation' => 'LI', 'country_name' => 'Liechtenstein'],
        ['country_abbreviation' => 'LT', 'country_name' => 'Lithuania'],
        ['country_abbreviation' => 'LU', 'country_name' => 'Luxembourg'],
        ['country_abbreviation' => 'MO', 'country_name' => 'Macao'],
        ['country_abbreviation' => 'MK', 'country_name' => 'Macedonia, The Former Yugoslav Republic of'],
        ['country_abbreviation' => 'MG', 'country_name' => 'Madagascar'],
        ['country_abbreviation' => 'MW', 'country_name' => 'Malawi'],
        ['country_abbreviation' => 'MY', 'country_name' => 'Malaysia'],
        ['country_abbreviation' => 'MV', 'country_name' => 'Maldives'],
        ['country_abbreviation' => 'ML', 'country_name' => 'Mali'],
        ['country_abbreviation' => 'MT', 'country_name' => 'Malta'],
        ['country_abbreviation' => 'MQ', 'country_name' => 'Martinique'],
        ['country_abbreviation' => 'MR', 'country_name' => 'Mauritania'],
        ['country_abbreviation' => 'MU', 'country_name' => 'Mauritius'],
        ['country_abbreviation' => 'YT', 'country_name' => 'Mayotte'],
        ['country_abbreviation' => 'MX', 'country_name' => 'Mexico'],
        ['country_abbreviation' => 'MD', 'country_name' => 'Moldova, Republic of'],
        ['country_abbreviation' => 'MC', 'country_name' => 'Monaco'],
        ['country_abbreviation' => 'MN', 'country_name' => 'Mongolia'],
        ['country_abbreviation' => 'MS', 'country_name' => 'Montserrat'],
        ['country_abbreviation' => 'MA', 'country_name' => 'Morocco'],
        ['country_abbreviation' => 'MZ', 'country_name' => 'Mozambique'],
        ['country_abbreviation' => 'MM', 'country_name' => 'Myanmar'],
        ['country_abbreviation' => 'NA', 'country_name' => 'Namibia'],
        ['country_abbreviation' => 'NR', 'country_name' => 'Nauru'],
        ['country_abbreviation' => 'NP', 'country_name' => 'Nepal'],
        ['country_abbreviation' => 'NL', 'country_name' => 'Netherlands'],
        ['country_abbreviation' => 'AN', 'country_name' => 'Netherlands Antilles'],
        ['country_abbreviation' => 'NC', 'country_name' => 'New Caledonia'],
        ['country_abbreviation' => 'NZ', 'country_name' => 'New Zealand'],
        ['country_abbreviation' => 'NI', 'country_name' => 'Nicaragua'],
        ['country_abbreviation' => 'NE', 'country_name' => 'Niger'],
        ['country_abbreviation' => 'NG', 'country_name' => 'Nigeria'],
        ['country_abbreviation' => 'NU', 'country_name' => 'Niue'],
        ['country_abbreviation' => 'NF', 'country_name' => 'Norfolk Island'],
        ['country_abbreviation' => 'NO', 'country_name' => 'Norway'],
        ['country_abbreviation' => 'OM', 'country_name' => 'Oman'],
        ['country_abbreviation' => 'PK', 'country_name' => 'Pakistan'],
        ['country_abbreviation' => 'PW', 'country_name' => 'Palau'],
        ['country_abbreviation' => 'PS', 'country_name' => 'Palestinian Territory, Occupied'],
        ['country_abbreviation' => 'PA', 'country_name' => 'Panama'],
        ['country_abbreviation' => 'PG', 'country_name' => 'Papua New Guinea'],
        ['country_abbreviation' => 'PY', 'country_name' => 'Paraguay'],
        ['country_abbreviation' => 'PE', 'country_name' => 'Peru'],
        ['country_abbreviation' => 'PH', 'country_name' => 'Philippines'],
        ['country_abbreviation' => 'PN', 'country_name' => 'Pitcairn'],
        ['country_abbreviation' => 'PL', 'country_name' => 'Poland'],
        ['country_abbreviation' => 'PT', 'country_name' => 'Portugal'],
        ['country_abbreviation' => 'QA', 'country_name' => 'Qatar'],
        ['country_abbreviation' => 'RE', 'country_name' => 'Reunion'],
        ['country_abbreviation' => 'RO', 'country_name' => 'Romania'],
        ['country_abbreviation' => 'RU', 'country_name' => 'Russian Federation'],
        ['country_abbreviation' => 'RW', 'country_name' => 'Rwanda'],
        ['country_abbreviation' => 'SH', 'country_name' => 'Saint Helena'],
        ['country_abbreviation' => 'KN', 'country_name' => 'Saint Kitts and Nevis'],
        ['country_abbreviation' => 'LC', 'country_name' => 'Saint Lucia'],
        ['country_abbreviation' => 'PM', 'country_name' => 'Saint Pierre and Miquelon'],
        ['country_abbreviation' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines'],
        ['country_abbreviation' => 'WS', 'country_name' => 'Samoa'],
        ['country_abbreviation' => 'SM', 'country_name' => 'San Marino'],
        ['country_abbreviation' => 'ST', 'country_name' => 'Sao Tome and Principe'],
        ['country_abbreviation' => 'SA', 'country_name' => 'Saudi Arabia'],
        ['country_abbreviation' => 'SN', 'country_name' => 'Senegal'],
        ['country_abbreviation' => 'CS', 'country_name' => 'Serbia and Montenegro'],
        ['country_abbreviation' => 'SC', 'country_name' => 'Seychelles'],
        ['country_abbreviation' => 'SL', 'country_name' => 'Sierra Leone'],
        ['country_abbreviation' => 'SG', 'country_name' => 'Singapore'],
        ['country_abbreviation' => 'SK', 'country_name' => 'Slovakia'],
        ['country_abbreviation' => 'SI', 'country_name' => 'Slovenia'],
        ['country_abbreviation' => 'SB', 'country_name' => 'Solomon Islands'],
        ['country_abbreviation' => 'SO', 'country_name' => 'Somalia'],
        ['country_abbreviation' => 'ZA', 'country_name' => 'South Africa'],
        ['country_abbreviation' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands'],
        ['country_abbreviation' => 'ES', 'country_name' => 'Spain'],
        ['country_abbreviation' => 'LK', 'country_name' => 'Sri Lanka'],
        ['country_abbreviation' => 'SD', 'country_name' => 'Sudan'],
        ['country_abbreviation' => 'SR', 'country_name' => 'Suriname'],
        ['country_abbreviation' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen'],
        ['country_abbreviation' => 'SZ', 'country_name' => 'Swaziland'],
        ['country_abbreviation' => 'SE', 'country_name' => 'Sweden'],
        ['country_abbreviation' => 'CH', 'country_name' => 'Switzerland'],
        ['country_abbreviation' => 'SY', 'country_name' => 'Syrian Arab Republic'],
        ['country_abbreviation' => 'TW', 'country_name' => 'Taiwan'],
        ['country_abbreviation' => 'TJ', 'country_name' => 'Tajikistan'],
        ['country_abbreviation' => 'TZ', 'country_name' => 'Tanzania, United Republic of'],
        ['country_abbreviation' => 'TH', 'country_name' => 'Thailand'],
        ['country_abbreviation' => 'TL', 'country_name' => 'Timor-Leste'],
        ['country_abbreviation' => 'TG', 'country_name' => 'Togo'],
        ['country_abbreviation' => 'TK', 'country_name' => 'Tokelau'],
        ['country_abbreviation' => 'TO', 'country_name' => 'Tonga'],
        ['country_abbreviation' => 'TT', 'country_name' => 'Trinidad and Tobago'],
        ['country_abbreviation' => 'TN', 'country_name' => 'Tunisia'],
        ['country_abbreviation' => 'TR', 'country_name' => 'Turkey'],
        ['country_abbreviation' => 'TM', 'country_name' => 'Turkmenistan'],
        ['country_abbreviation' => 'TC', 'country_name' => 'Turks and Caicos Islands'],
        ['country_abbreviation' => 'TV', 'country_name' => 'Tuvalu'],
        ['country_abbreviation' => 'UG', 'country_name' => 'Uganda'],
        ['country_abbreviation' => 'UA', 'country_name' => 'Ukraine'],
        ['country_abbreviation' => 'AE', 'country_name' => 'United Arab Emirates'],
        ['country_abbreviation' => 'US', 'country_name' => 'United States'],
        ['country_abbreviation' => 'UM', 'country_name' => 'United States Minor Outlying Islands'],
        ['country_abbreviation' => 'UY', 'country_name' => 'Uruguay'],
        ['country_abbreviation' => 'UZ', 'country_name' => 'Uzbekistan'],
        ['country_abbreviation' => 'VU', 'country_name' => 'Vanuatu'],
        ['country_abbreviation' => 'VE', 'country_name' => 'Venezuela'],
        ['country_abbreviation' => 'VN', 'country_name' => 'Viet Nam'],
        ['country_abbreviation' => 'VG', 'country_name' => 'Virgin Islands, British'],
        ['country_abbreviation' => 'WF', 'country_name' => 'Wallis and Futuna'],
        ['country_abbreviation' => 'EH', 'country_name' => 'Western Sahara'],
        ['country_abbreviation' => 'YE', 'country_name' => 'Yemen'],
        ['country_abbreviation' => 'ZM', 'country_name' => 'Zambia'],
        ['country_abbreviation' => 'ZW', 'country_name' => 'Zimbabwe'],
    ];
    public array $enumerationTypes = ['NPI-1','NPI-2'];
    public array $addressPurposes = ['Primary','Secondary'];
    public array $queryParameters = [
        'version' => '2.1',
        'number' => '',
        'enumeration_type' => '',
        'taxonomy_description' => '',
        'first_name' => '',
        'use_first_name_alias' => 'true',
        'last_name' => '',
        'address_purpose' => '',
        'city' => '',
        'state' => '',
        'postal_code' => '',
        'country_code' => '',
        'limit'                 => '50',
        //'skip'                  => '',
        //'pretty'                => '',
    ];
    protected int $limit;
    protected int $skip;

    public mixed $results;
    public mixed $resultErrors;


    /**
     * @throws GuzzleException
     */
    public function search()
    {
        $npiRegistry = new Client();
        $response = $npiRegistry->getData($this->queryParameters);

        if (isset($response['Errors'])) {
            $errors = $response['Errors'][0];
            $description = $errors['description'];
            $field = $errors['field'];
            $number = $errors['number'];
            $customError = 'Number: ' . $number . ', Field: ' . $field . ', Description: ' . $description;

            $this->resultErrors = $customError;
        } else {
            $this->results = $npiRegistry->getData($this->queryParameters);
        }
    }

    public function closeError()
    {
        $this->resultErrors = '';
    }

    public function refreshDefaults()
    {
        $this->resultErrors = '';
        $this->resetPage();
    }
    public function render()
    {
        return view('livewire.forms.npi-search');
    }
}
